# Generated by Django 2.2.12 on 2020-04-25 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequiredDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadFile', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Upload Document')),
                ('status', models.CharField(choices=[('None', 'None'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='None', max_length=10, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webaccount.Client_Personal_Info')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webaccount.Required_Documents', verbose_name='Submit Document')),
            ],
            options={
                'verbose_name': 'Client Document',
                'verbose_name_plural': 'Client Documents',
            },
        ),
    ]
