# Generated by Django 2.2.12 on 2020-04-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0003_auto_20200425_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulatationrequest',
            name='Name',
            field=models.CharField(blank=True, default=None, error_messages={'blank': 'Name is required', 'unique': 'Name Already Exists.'}, max_length=100, null=True, verbose_name='Consultation Name'),
        ),
    ]
