# Generated by Django 2.2.12 on 2020-04-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0005_auto_20200425_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulatationrequest',
            name='decline_explanation',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Decline Reaons'),
        ),
    ]
