# Generated by Django 2.2.12 on 2020-04-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0007_auto_20200425_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulatationrequest',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Rating'),
        ),
    ]
