# Generated by Django 2.2.12 on 2020-04-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0009_auto_20200425_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50, unique=True, verbose_name='Shipping Method')),
            ],
        ),
        migrations.CreateModel(
            name='PickUpRequestOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT'), ('ON DELIVERY', 'ON DELIVERY'), ('RECEIVED', 'RECEIVED'), ('FAILED', 'FAILED'), ('NONE', 'NONE')], default='NONE', max_length=15, verbose_name='Request Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webaccount.Client_Personal_Info')),
                ('shippingMethod', models.ForeignKey(error_messages={'blank': 'Shipping method is required', 'null': 'Shipping method is required'}, on_delete=django.db.models.deletion.CASCADE, to='webaccount.Shipping', verbose_name='Shipping Method')),
            ],
        ),
    ]
