# Generated by Django 2.2.12 on 2020-04-25 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0010_pickuprequestorders_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequestorders',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickuprequestorders',
            name='updated_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Updated Timestamp'),
        ),
    ]
