# Generated by Django 2.2.12 on 2020-05-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0011_auto_20200425_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreport',
            name='month_quarterType',
            field=models.CharField(choices=[('JANUARY', 'JANUARY'), ('FEBRUARY', 'FEBRUARY'), ('MARCH', 'MARCH'), ('APRIL', 'APRIL'), ('MAY', 'MAY'), ('JUNE', 'JUNE'), ('JULY', 'JULY'), ('AUGUST', 'AUGUST'), ('SEPTEMBER', 'SEPTEMBER'), ('OCTOBER', 'OCTOBER'), ('NOVEMBER', 'NOVEMBER'), ('DECEMBER', 'DECEMBER'), ('Q1', 'Q1'), ('Q2', 'Q2')], default=5, max_length=20, verbose_name='Month or Quarter'),
        ),
        migrations.AlterField(
            model_name='consulatationrequest',
            name='explanation',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Explanation'),
        ),
    ]
