# Generated by Django 2.2.12 on 2020-05-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0013_auto_20200505_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulatationrequest',
            name='clientPaid',
        ),
    ]
