# Generated by Django 2.2.12 on 2020-05-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0015_auto_20200505_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulatationrequest',
            name='Name',
        ),
    ]
