# Generated by Django 2.2.12 on 2020-05-05 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0018_consulatationrequest_consultantmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulatationrequest',
            name='consultantManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Consultant Manager'),
        ),
    ]
