# Generated by Django 2.2.12 on 2020-05-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0019_auto_20200505_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantmodel',
            name='parentField',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Parent Field'),
        ),
    ]
