# Generated by Django 2.2.12 on 2020-05-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0020_auto_20200506_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantmodel',
            name='parentField',
            field=models.CharField(default=None, max_length=100, verbose_name='Parent Field'),
        ),
    ]
