# Generated by Django 2.2.12 on 2020-05-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0023_auto_20200506_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentName', models.CharField(default='', max_length=100, verbose_name='Parent Field Name')),
            ],
        ),
    ]
