# Generated by Django 2.2.12 on 2020-05-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0024_parentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantmodel',
            name='parentField',
        ),
    ]
