# Generated by Django 2.2.12 on 2020-05-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0025_remove_consultantmodel_parentfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webaccount.ParentModel'),
        ),
    ]
