# Generated by Django 2.2.12 on 2020-05-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0026_consultantmodel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulatationrequest',
            name='client',
            field=models.ForeignKey(limit_choices_to={'status': 'Active'}, on_delete=django.db.models.deletion.CASCADE, to='webaccount.Client_Personal_Info'),
        ),
    ]
