# Generated by Django 2.2.12 on 2020-05-08 03:37

from django.db import migrations, models
import webaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0028_auto_20200507_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequestorders',
            name='contactName',
            field=models.CharField(default='', max_length=100, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='pickuprequestorders',
            name='contactNumber',
            field=models.CharField(default='', max_length=10, validators=[webaccount.models.phoneNumberValidator], verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='pickuprequestorders',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='pickuprequestorders',
            name='numberInvoices',
            field=models.IntegerField(default=0, validators=[webaccount.models.integerValidator], verbose_name='Number of Invoices'),
        ),
    ]
