# Generated by Django 2.2.12 on 2020-05-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0029_auto_20200508_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulatationrequest',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pickuprequestorders',
            name='contactName',
            field=models.CharField(default='', max_length=100, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='pickuprequestorders',
            name='status',
            field=models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT'), ('ON DELIVERY', 'ON DELIVERY'), ('RECEIVED', 'RECEIVED'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING'), ('NONE', 'NONE')], default='NONE', max_length=15, verbose_name='Request Status'),
        ),
        migrations.AlterField(
            model_name='pickuprequestorders',
            name='updated_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated Timestamp'),
        ),
    ]
