# Generated by Django 2.2.12 on 2020-05-11 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0030_auto_20200511_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequestorders',
            name='pickupTimestamp',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Pickup Date & Time'),
        ),
    ]
