# Generated by Django 2.2.12 on 2020-05-11 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0031_pickuprequestorders_pickuptimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequestorders',
            name='pickupTimestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Pickup Date & Time'),
        ),
    ]
