# Generated by Django 2.2.12 on 2020-05-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0033_auto_20200511_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantmodel',
            name='parent',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.SET_DEFAULT, to='webaccount.ParentModel'),
        ),
    ]
