# Generated by Django 2.2.13 on 2020-06-18 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0036_auto_20200618_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmreport',
            name='uploadFile',
            field=models.FileField(upload_to='uploads/rmReports/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx '])], verbose_name='Upload Document'),
        ),
    ]
