# Generated by Django 2.2.13 on 2020-06-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0037_auto_20200618_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmreport',
            name='uploadFile',
            field=models.FileField(upload_to='uploads/rmReports/%Y/%m/%d/', verbose_name='Upload Document'),
        ),
    ]
