# Generated by Django 2.2.13 on 2020-06-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0039_auto_20200618_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmreport',
            name='status',
            field=models.CharField(choices=[('Not Confirm', 'Not Confirm'), ('Confirm', 'Confirm')], default='Not Confirm', max_length=15),
        ),
    ]
