# Generated by Django 2.2.13 on 2020-06-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0040_rmreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmreport',
            name='status',
            field=models.CharField(choices=[('Not Confirmed', 'Not Confirm'), ('Confirmed', 'Confirm')], default='Not Confirmed', max_length=15),
        ),
    ]
