# Generated by Django 2.2.13 on 2020-09-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0044_auto_20200911_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmreport',
            name='reportType',
            field=models.CharField(choices=[('VAT Report', 'VAT Report'), ('Ratio Analysis Report', 'Ratio Analysis Report'), ('Income Statement', 'Income Statement'), ('Balance Sheet', 'Balance Sheet'), ('Profit & Loss', 'Profit & Loss')], default='Report Type', max_length=25),
        ),
    ]
