# Generated by Django 2.2.13 on 2020-10-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0045_auto_20200911_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmreport',
            name='chartData_1',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Chart 1 Saved Data'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='chartLabel_1',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Chart 1 Saved Fields'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='is_saved_chart_1',
            field=models.BooleanField(default=False, verbose_name='Is Chart 1 saved?'),
        ),
        migrations.AlterField(
            model_name='clientreport',
            name='month_quarterType',
            field=models.CharField(choices=[('JANUARY', 'JANUARY'), ('FEBRUARY', 'FEBRUARY'), ('MARCH', 'MARCH'), ('APRIL', 'APRIL'), ('MAY', 'MAY'), ('JUNE', 'JUNE'), ('JULY', 'JULY'), ('AUGUST', 'AUGUST'), ('SEPTEMBER', 'SEPTEMBER'), ('OCTOBER', 'OCTOBER'), ('NOVEMBER', 'NOVEMBER'), ('DECEMBER', 'DECEMBER'), ('Q1', 'Q1'), ('Q2', 'Q2')], default=10, max_length=20, verbose_name='Month or Quarter'),
        ),
        migrations.AlterField(
            model_name='rmreport',
            name='month_quarterType',
            field=models.CharField(choices=[('JANUARY', 'JANUARY'), ('FEBRUARY', 'FEBRUARY'), ('MARCH', 'MARCH'), ('APRIL', 'APRIL'), ('MAY', 'MAY'), ('JUNE', 'JUNE'), ('JULY', 'JULY'), ('AUGUST', 'AUGUST'), ('SEPTEMBER', 'SEPTEMBER'), ('OCTOBER', 'OCTOBER'), ('NOVEMBER', 'NOVEMBER'), ('DECEMBER', 'DECEMBER'), ('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], default=10, max_length=20, verbose_name='Month or Quarter'),
        ),
    ]
