# Generated by Django 2.2.13 on 2020-10-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0047_auto_20201016_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmreport',
            name='chartData_3',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Chart 3 Saved Data'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='chartData_4',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Chart 4 Saved Data'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='chartData_5',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Chart 5 Saved Data'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='chartData_6',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Chart 6 Saved Data'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='chartLabel_3',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Chart 3 Saved Fields'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='chartLabel_4',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Chart 4 Saved Fields'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='chartLabel_5',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Chart 5 Saved Fields'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='chartLabel_6',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Chart 6 Saved Fields'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='is_saved_chart_3',
            field=models.BooleanField(default=False, verbose_name='Is Chart 3 saved?'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='is_saved_chart_4',
            field=models.BooleanField(default=False, verbose_name='Is Chart 4 saved?'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='is_saved_chart_5',
            field=models.BooleanField(default=False, verbose_name='Is Chart 5 saved?'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='is_saved_chart_6',
            field=models.BooleanField(default=False, verbose_name='Is Chart 6 saved?'),
        ),
    ]
