# Generated by Django 2.2.13 on 2020-10-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0048_auto_20201016_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmreport',
            name='chart_1_type',
            field=models.CharField(default='', max_length=100, verbose_name='Chart 1 Type'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='chart_2_type',
            field=models.CharField(default='', max_length=100, verbose_name='Chart 2 Type'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='chart_3_type',
            field=models.CharField(default='', max_length=100, verbose_name='Chart 3 Type'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='chart_4_type',
            field=models.CharField(default='', max_length=100, verbose_name='Chart 4 Type'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='chart_5_type',
            field=models.CharField(default='', max_length=100, verbose_name='Chart 5 Type'),
        ),
        migrations.AddField(
            model_name='rmreport',
            name='chart_6_type',
            field=models.CharField(default='', max_length=100, verbose_name='Chart 6 Type'),
        ),
    ]
