# Generated by Django 2.2.13 on 2020-11-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0050_auto_20201111_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='rminvoice',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
