# Generated by Django 2.2.13 on 2020-11-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0051_rminvoice_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rminvoice',
            name='lastUpdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last Update'),
        ),
    ]
