# Generated by Django 2.2.13 on 2020-11-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0052_auto_20201113_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rminvoice',
            name='uploadFile',
            field=models.FileField(upload_to='uploads/rmInvoice/%Y/%m/%d/', verbose_name='Upload Image/Document'),
        ),
    ]
