# Generated by Django 2.2.13 on 2020-11-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0053_auto_20201118_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinvoice',
            name='statusType',
            field=models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Processed', 'Processing'), ('Postponed', 'Pending')], default='New', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='rminvoice',
            name='statusType',
            field=models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Processed', 'Processing'), ('Postponed', 'Pending')], default='New', max_length=15, verbose_name='Status'),
        ),
    ]
