# Generated by Django 2.2.13 on 2020-11-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0055_auto_20201118_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rminvoice',
            name='comment',
        ),
    ]
