# Generated by Django 2.2.13 on 2020-12-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0058_auto_20201204_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagemodel',
            options={'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
    ]
