# Generated by Django 2.2.13 on 2020-12-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0060_auto_20201207_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='price',
            field=models.FloatField(default='', verbose_name='Price'),
        ),
    ]
