"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from django.conf import global_settings


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(3f*0tcfa_y)mm+sj^v(iavy+ww$m18&dv1_q609xz336fwz31'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# ALLOWED_HOSTS = []
PROTOCOL = ""
ALLOWED_HOSTS = ['167.172.128.142', "127.0.0.1"]
ALLOWED_DOMAINS = ['167.172.128.142', "127.0.0.1"]
PORT = ["8000"]


os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '.gitignore'

# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'channels',
    'accounts',
    "webaccount.apps.MyAdminConfig",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webaccount',
        # Apps
    'core',
    # 3rd party
    'rest_framework',
    # 'channels',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'webaccount/templates'),
            os.path.join(BASE_DIR, 'templates')
            ],
        # 'DIRS' : [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTH_USER_MODEL = 'accounts.User'

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100
}

MESSAGES_TO_LOAD = 15

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgiref.ChannelLayer",
        "ROUTING": "core.routing.channel_routing",
    },
}


# In settings.py
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "asgiref.inmemory.ChannelLayer",
#         "ROUTING": "core.routing.channel_routing",
#     },
# }

# In settings.py
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "asgiref..ChannelLayer",
#         'CONFIG': {
#             'hosts': [('127.0.0.1', 55713)],
#         },
#         "ROUTING": "core.routing.channel_routing",
#     },
# }


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# STATIC_URL = '/static/'


#--------------------------------------------------------------------------
# from django.contrib.auth import urls
from django.urls import reverse_lazy

# LOGIN_REDIRECT_URL = '/'
# LOGIN_URL = reverse_lazy("login")
# LOGOUT_URL = reverse_lazy("login")

LOGIN_URL = reverse_lazy('index_url')

LOGIN_REDIRECT_URL = reverse_lazy('index_url')

LOGOUT_REDIRECT_URL = reverse_lazy('index_url')
#--------------------------------------------------------------------------


#------------------------------------------------------------------------
#Media settings
STATIC_ROOT=os.path.join(BASE_DIR,'static')
STATIC_URL = '/static/'
STATICFILES_DIRS =[
    os.path.join(BASE_DIR,'webaccount/static'),
    os.path.join(BASE_DIR,'core/static'),
    ]
MEDIA_URL = '/media/'
MEDIA_ROOT=os.path.join(os.path.dirname(BASE_DIR),'media')
#-------------------------------------------------------------------------

#------------------------------------------------------------------------
#Email Setting...
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'futuresoftcode@gmail.com'
EMAIL_HOST_PASSWORD = 'Sul@03228435921'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
#-------------------------------------------------------------------------


# Import local_settings.py
try:
    from local_settings import *
except ImportError:
    pass

ASGI_APPLICATION = 'mysite.routing.application'
# ASGI_APPLICATION = "mysite.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
   }
}