# Generated by Django 2.2.12 on 2020-05-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', null=True, verbose_name='superuser status'),
        ),
    ]
